ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'CONTENT_UPDATE';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'CONTENT_ARCHIVE';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'OWNERSHIP_TRANSFER';
